### PR TITLE
FIX: varius broken undefined variables

### PR DESCRIPTION
**Pull request by PandelisZ**

### CODE REVIEW

**Comment by PandelisZ** [comment]
@luketainton approve me

**Comment by luketainton** [comment]
Tom did the approve 😊

**Comment by CoffeeOwl97** [comment]
😎

**Comment by PandelisZ** [comment]
Nice. Well this actually like works now lol

**Comment by CoffeeOwl97** [comment]
Nice, we fixed the code for the thing that hasn't been used in like a year 😄

**Comment by PandelisZ** [comment]
*two.

**Pull request merged**
